// <auto-generated />
using System;
using GestiSoft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestiSoft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestiSoftDbContext))]
    [Migration("20260826144224_AddSchemaOperativo")]
    partial class AddSchemaOperativo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cauzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ImportoCauzione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PrenotazioneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrenotazioneId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("cauzioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("clienti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiAziendali", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<string>("Comune")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Denominazione")
                        .HasColumnType("text");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Iso2")
                        .HasColumnType("text");

                    b.Property<string>("NCivico")
                        .HasColumnType("text");

                    b.Property<string>("Nazione")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("PIva")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<int?>("RegimeFiscale")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("dati_aziendali", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("CodiceDestinatario")
                        .HasColumnType("text");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerKey")
                        .HasColumnType("text");

                    b.Property<string>("Denominazione")
                        .HasColumnType("text");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Iso2")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("NCivico")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("PIva")
                        .HasColumnType("text");

                    b.Property<string>("Pec")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.ToTable("dati_cliente", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiFattura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AliquotaIva")
                        .HasColumnType("integer");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<decimal>("Arrotondamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DatiClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("Divisa")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<int?>("Natura")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrezzoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Progressivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantita")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("RegimeFiscale")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatiClienteId");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Anno", "Progressivo")
                        .IsUnique();

                    b.ToTable("dati_fattura", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Entrata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Anno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoEntrata")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEntrata")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Data");

                    b.ToTable("entrate", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.GestionePrezzo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrezzoPerNotte")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("CameraId", "DataInizio", "DataFine");

                    b.ToTable("prezzi_camera", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsenteDaTassa")
                        .HasColumnType("boolean");

                    b.Property<string>("LuogoNascita")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<int?>("Permanenza")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrenotazioneId")
                        .HasColumnType("uuid");

                    b.Property<string>("RilascioDocumento")
                        .HasColumnType("text");

                    b.Property<int?>("Sesso")
                        .HasColumnType("integer");

                    b.Property<string>("StatoNascita")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoOspite")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrenotazioneId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("ospiti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OspiteRiga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsenteDaTassa")
                        .HasColumnType("boolean");

                    b.Property<string>("LuogoNascita")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid?>("OspiteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Permanenza")
                        .HasColumnType("integer");

                    b.Property<bool?>("PostoLetto")
                        .HasColumnType("boolean");

                    b.Property<int?>("Sesso")
                        .HasColumnType("integer");

                    b.Property<string>("StatoNascita")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("OspiteId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("ospiti_righe", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Prenotazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agenzia")
                        .HasColumnType("text");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckEditSelection")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ImportoPagato")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ImportoPrenotazione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ImportoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("NumeroOspiti")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroPrenotazione")
                        .HasColumnType("text");

                    b.Property<bool>("PMS")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayTourist")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatePolice")
                        .HasColumnType("boolean");

                    b.Property<int?>("StatoPrenotazione")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Supply")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "CheckIn", "CheckOut");

                    b.ToTable("prenotazioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Comune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<long>("Codice")
                        .HasColumnType("bigint");

                    b.Property<string>("CodiceBelfiore")
                        .HasColumnType("text");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("comuni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("documenti_identita", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Stato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronimo")
                        .HasColumnType("text");

                    b.Property<long>("Codice")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeInglese")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("stati", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.TipoAlloggiato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("tipi_alloggiato", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingAgenzia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Descrizione")
                        .IsUnique();

                    b.ToTable("canali_vendita", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CapacitaOspiti")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SoggiornoMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("StateRoom")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipologiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("TipologiaId");

                    b.HasIndex("StrutturaId", "Nome")
                        .IsUnique();

                    b.ToTable("camere", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingTipologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Animali")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Cauzione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Implemento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("NumeroImplementoPersona")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrezzoDefault")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SpesePulizia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipologiaCamera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "TipologiaCamera")
                        .IsUnique();

                    b.ToTable("tipologie_camera", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Spesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Anno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSpesa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoSpesa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoSpesa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "DataSpesa");

                    b.ToTable("spese", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Struttura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("strutture", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cauzione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithMany()
                        .HasForeignKey("PrenotazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiAziendali", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiFattura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.DatiCliente", "Cliente")
                        .WithMany("Fatture")
                        .HasForeignKey("DatiClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Entrata", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.GestionePrezzo", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithMany()
                        .HasForeignKey("PrenotazioneId");

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OspiteRiga", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Ospite", "Ospite")
                        .WithMany("Membri")
                        .HasForeignKey("OspiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Ospite");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Prenotazione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingAgenzia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingRoom", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.SettingTipologia", "Tipologia")
                        .WithMany()
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingTipologia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Spesa", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Struttura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Strutture")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Strutture");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.Navigation("Membri");
                });
#pragma warning restore 612, 618
        }
    }
}
