// <auto-generated />
using System;
using GestiSoft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestiSoft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestiSoftDbContext))]
    [Migration("20260828072312_AddComuneAttivitaImpostazioni")]
    partial class AddComuneAttivitaImpostazioni
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestiSoft.Domain.Entities.AlloggiatiWebIntegrazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UltimeSchedineInviate")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoErrore")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInvioAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Utente")
                        .HasColumnType("text");

                    b.Property<string>("WsKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("alloggiati_web_integrazioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cauzione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ImportoCauzione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PrenotazioneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrenotazioneId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("cauzioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("clienti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiAziendali", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<string>("Comune")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Denominazione")
                        .HasColumnType("text");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Iso2")
                        .HasColumnType("text");

                    b.Property<string>("NCivico")
                        .HasColumnType("text");

                    b.Property<string>("Nazione")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("PIva")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<int?>("RegimeFiscale")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("dati_aziendali", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("CodiceDestinatario")
                        .HasColumnType("text");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerKey")
                        .HasColumnType("text");

                    b.Property<string>("Denominazione")
                        .HasColumnType("text");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("text");

                    b.Property<string>("Iso2")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("NCivico")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("PIva")
                        .HasColumnType("text");

                    b.Property<string>("Pec")
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.ToTable("dati_cliente", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiFattura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AliquotaIva")
                        .HasColumnType("integer");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<decimal>("Arrotondamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DatiClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<string>("Divisa")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<int?>("Natura")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrezzoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Progressivo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantita")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("RegimeFiscale")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DatiClienteId");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Anno", "Progressivo")
                        .IsUnique();

                    b.ToTable("dati_fattura", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Entrata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Anno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoEntrata")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoEntrata")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Data");

                    b.ToTable("entrate", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.GestionePrezzo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrezzoPerNotte")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipologiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("CameraId", "DataInizio", "DataFine");

                    b.HasIndex("TipologiaId", "DataInizio", "DataFine");

                    b.ToTable("prezzi_camera", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.ImpostazioniStruttura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComuneAttivita")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("OraInvioGiornaliero")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("OsservatorioAttivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayTouristAttivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("PoliziaStatoAttiva")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TassaSoggiornoMaxGiorni")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TassaSoggiornoPrezzo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("impostazioni_struttura", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.LogEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dettaglio")
                        .HasColumnType("text");

                    b.Property<int>("Livello")
                        .HasColumnType("integer");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("StrutturaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ClienteId", "StrutturaId", "CreatedAtUtc");

                    b.ToTable("log_eventi", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsenteDaTassa")
                        .HasColumnType("boolean");

                    b.Property<string>("LuogoNascita")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<int?>("Permanenza")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrenotazioneId")
                        .HasColumnType("uuid");

                    b.Property<string>("RilascioDocumento")
                        .HasColumnType("text");

                    b.Property<int?>("Sesso")
                        .HasColumnType("integer");

                    b.Property<string>("StatoNascita")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoOspite")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrenotazioneId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("ospiti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OspiteRiga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cittadinanza")
                        .HasColumnType("text");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsenteDaTassa")
                        .HasColumnType("boolean");

                    b.Property<string>("LuogoNascita")
                        .HasColumnType("text");

                    b.Property<string>("LuogoResidenza")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid?>("OspiteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Permanenza")
                        .HasColumnType("integer");

                    b.Property<bool?>("PostoLetto")
                        .HasColumnType("boolean");

                    b.Property<int?>("Sesso")
                        .HasColumnType("integer");

                    b.Property<string>("StatoNascita")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("OspiteId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("ospiti_righe", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioAppartamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CursoreDataAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityCode")
                        .HasColumnType("text");

                    b.Property<string>("HotelCode")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("ProssimoStayIdProgressivo")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UltimeSchedineInviate")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoErrore")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInvioAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.ToTable("osservatorio_appartamenti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioAppartamentoTipologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OsservatorioAppartamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipologiaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaId");

                    b.HasIndex("OsservatorioAppartamentoId", "TipologiaId")
                        .IsUnique();

                    b.ToTable("osservatorio_appartamenti_tipologie", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioInvio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInvioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OspiteRigaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrenotazioneId")
                        .HasColumnType("uuid");

                    b.Property<string>("StayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrenotazioneId");

                    b.HasIndex("StrutturaId");

                    b.ToTable("osservatorio_invii", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristIntegrazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PortaleOnlineAttivo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("paytourist_integrazioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristStruttura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdStrutturaPaytourist")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UltimeInviate")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoErrore")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoInvioAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.ToTable("paytourist_strutture", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristStrutturaTipologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayTouristStrutturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipologiaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaId");

                    b.HasIndex("PayTouristStrutturaId", "TipologiaId")
                        .IsUnique();

                    b.ToTable("paytourist_strutture_tipologie", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Prenotazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agenzia")
                        .HasColumnType("text");

                    b.Property<int>("Anno")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CameraId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckEditSelection")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdPrenotazioneWubook")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ImportoPagato")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ImportoPrenotazione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ImportoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("NumeroOspiti")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroPrenotazione")
                        .HasColumnType("text");

                    b.Property<bool>("PMS")
                        .HasColumnType("boolean");

                    b.Property<bool>("PayTourist")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatePolice")
                        .HasColumnType("boolean");

                    b.Property<int?>("StatoPrenotazione")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Supply")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "IdPrenotazioneWubook")
                        .IsUnique()
                        .HasFilter("\"IdPrenotazioneWubook\" IS NOT NULL");

                    b.HasIndex("StrutturaId", "CheckIn", "CheckOut");

                    b.ToTable("prenotazioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Comune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cap")
                        .HasColumnType("text");

                    b.Property<long>("Codice")
                        .HasColumnType("bigint");

                    b.Property<string>("CodiceBelfiore")
                        .HasColumnType("text");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("comuni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("documenti_identita", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.Stato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronimo")
                        .HasColumnType("text");

                    b.Property<long>("Codice")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeInglese")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("stati", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Riferimenti.TipoAlloggiato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("tipi_alloggiato", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingAgenzia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "Descrizione")
                        .IsUnique();

                    b.ToTable("canali_vendita", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CapacitaOspiti")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCameraWubook")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SoggiornoMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("StateRoom")
                        .HasColumnType("integer");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TipologiaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WubookAttiva")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("TipologiaId");

                    b.HasIndex("StrutturaId", "IdCameraWubook");

                    b.HasIndex("StrutturaId", "Nome")
                        .IsUnique();

                    b.ToTable("camere", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingTipologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Animali")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Cauzione")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Implemento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("NumeroImplementoPersona")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrezzoDefault")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("SpesePulizia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipologiaCamera")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "TipologiaCamera")
                        .IsUnique();

                    b.ToTable("tipologie_camera", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Spesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Anno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataSpesa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descrizione")
                        .HasColumnType("text");

                    b.Property<decimal>("ImportoSpesa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetodoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoSpesa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("StrutturaId", "DataSpesa");

                    b.ToTable("spese", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Struttura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("strutture", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Utente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cognome")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utenti", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.UtenteStruttura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BookingRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("BookingWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("FinanceRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("FinanceWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReservationRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReservationWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("RestaurantRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("RestaurantWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("RoomStatusUpdate")
                        .HasColumnType("boolean");

                    b.Property<int>("Ruolo")
                        .HasColumnType("integer");

                    b.Property<bool>("SettingAgency")
                        .HasColumnType("boolean");

                    b.Property<bool>("SettingRoomRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("SettingRoomWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("SettingUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatePoliceRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatePoliceSettings")
                        .HasColumnType("boolean");

                    b.Property<bool>("StatePoliceWrite")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId");

                    b.HasIndex("UtenteId", "StrutturaId")
                        .IsUnique();

                    b.ToTable("utenti_strutture", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.WubookIntegrazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyCache")
                        .HasColumnType("text");

                    b.Property<bool>("Attivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CacheAggiornataAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GestisoftToken")
                        .HasColumnType("text");

                    b.Property<string>("GestisoftUsername")
                        .HasColumnType("text");

                    b.Property<string>("IdPaytouristCache")
                        .HasColumnType("text");

                    b.Property<string>("LcodeCache")
                        .HasColumnType("text");

                    b.Property<Guid>("StrutturaId")
                        .HasColumnType("uuid");

                    b.Property<string>("UltimoErrore")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StrutturaId")
                        .IsUnique();

                    b.ToTable("wubook_integrazioni", (string)null);
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.AlloggiatiWebIntegrazione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cauzione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithMany()
                        .HasForeignKey("PrenotazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiAziendali", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiFattura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.DatiCliente", "Cliente")
                        .WithMany("Fatture")
                        .HasForeignKey("DatiClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Entrata", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.GestionePrezzo", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.SettingTipologia", "Tipologia")
                        .WithMany()
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Camera");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.ImpostazioniStruttura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Prenotazione", "Prenotazione")
                        .WithMany()
                        .HasForeignKey("PrenotazioneId");

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OspiteRiga", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Ospite", "Ospite")
                        .WithMany("Membri")
                        .HasForeignKey("OspiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Ospite");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioAppartamento", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioAppartamentoTipologia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.OsservatorioAppartamento", "OsservatorioAppartamento")
                        .WithMany("Tipologie")
                        .HasForeignKey("OsservatorioAppartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.SettingTipologia", "Tipologia")
                        .WithMany()
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OsservatorioAppartamento");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioInvio", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristIntegrazione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristStruttura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristStrutturaTipologia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.PayTouristStruttura", "PayTouristStruttura")
                        .WithMany("Tipologie")
                        .HasForeignKey("PayTouristStrutturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.SettingTipologia", "Tipologia")
                        .WithMany()
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PayTouristStruttura");

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Prenotazione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.SettingRoom", "Camera")
                        .WithMany()
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingAgenzia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingRoom", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.SettingTipologia", "Tipologia")
                        .WithMany()
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tipologia");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.SettingTipologia", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Spesa", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Struttura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Strutture")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Utente", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.UtenteStruttura", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", "Struttura")
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestiSoft.Domain.Entities.Utente", "Utente")
                        .WithMany("Strutture")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Struttura");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.WubookIntegrazione", b =>
                {
                    b.HasOne("GestiSoft.Domain.Entities.Struttura", null)
                        .WithMany()
                        .HasForeignKey("StrutturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Strutture");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.DatiCliente", b =>
                {
                    b.Navigation("Fatture");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Ospite", b =>
                {
                    b.Navigation("Membri");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.OsservatorioAppartamento", b =>
                {
                    b.Navigation("Tipologie");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.PayTouristStruttura", b =>
                {
                    b.Navigation("Tipologie");
                });

            modelBuilder.Entity("GestiSoft.Domain.Entities.Utente", b =>
                {
                    b.Navigation("Strutture");
                });
#pragma warning restore 612, 618
        }
    }
}
